/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = 
{
    "auth": {
      "user_pool_id": "ap-southeast-1_thFz3qEPe",
      "aws_region": "ap-southeast-1",
      "user_pool_client_id": "2bbsh5gqfp0shgaht49b5j2kuq",
      "identity_pool_id": "ap-southeast-1:009eae4e-ca41-4ff2-8bff-5223087c5e1b",
      "mfa_methods": [],
      "standard_required_attributes": [
        "email",
        "phone_number"
      ],
      "username_attributes": [
        "email",
        "phone_number"
      ],
      "user_verification_types": [
        "email",
        "phone_number"
      ],
      "mfa_configuration": "OPTIONAL",
      "password_policy": {
        "min_length": 10,
        "require_numbers": true,
        "require_lowercase": true,
        "require_uppercase": true,
        "require_symbols": true
      },
      "unauthenticated_identities_enabled": true
    },
    "data": {
      "url": "https://hhnjasljhradjkfws74rnaknh4.appsync-api.ap-southeast-1.amazonaws.com/graphql",
      "aws_region": "ap-southeast-1",
      "api_key": "da2-xvq2xcby5jaurb46i7i6agosxy",
      "default_authorization_type": "API_KEY",
      "authorization_types": [
        "AMAZON_COGNITO_USER_POOLS",
        "AWS_IAM"
      ],
      "model_introspection": {
        "version": 1,
        "models": {
          "Todo": {
            "name": "Todo",
            "fields": {
              "id": {
                "name": "id",
                "isArray": false,
                "type": "ID",
                "isRequired": true,
                "attributes": []
              },
              "content": {
                "name": "content",
                "isArray": false,
                "type": "String",
                "isRequired": false,
                "attributes": []
              },
              "createdAt": {
                "name": "createdAt",
                "isArray": false,
                "type": "AWSDateTime",
                "isRequired": false,
                "attributes": [],
                "isReadOnly": true
              },
              "updatedAt": {
                "name": "updatedAt",
                "isArray": false,
                "type": "AWSDateTime",
                "isRequired": false,
                "attributes": [],
                "isReadOnly": true
              }
            },
            "syncable": true,
            "pluralName": "Todos",
            "attributes": [
              {
                "type": "model",
                "properties": {}
              },
              {
                "type": "auth",
                "properties": {
                  "rules": [
                    {
                      "allow": "public",
                      "provider": "apiKey",
                      "operations": [
                        "create",
                        "update",
                        "delete",
                        "read"
                      ]
                    }
                  ]
                }
              }
            ],
            "primaryKeyInfo": {
              "isCustomPrimaryKey": false,
              "primaryKeyFieldName": "id",
              "sortKeyFieldNames": []
            }
          }
        },
        "enums": {},
        "nonModels": {}
      }
    },
    "version": "1"
  };


export default awsmobile;
